Game/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("RiskGame.urls")),
    path('', auth_views.LoginView.as_view(
        template_name='home.html'), name='home'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

]

RiskGame/urls.py
from django.urls import path, re_path
from .views import ImpostazioniView
from . import views

app_name = "RiskGame"

urlpatterns = [
    #path("", HomePageView.as_view(), name="home"),
    #path('registrazione', views.register, name='register'),
    path("registrazione", views.RegistrazioneView.register, name="registrazione"),
    path("crea-partita", views.CreazioneView.draw, name="creazione"),
    path("menu", views.MenuView.drawMenu, name="menu"),
    path("menuospite", views.MenuView.drawOspite, name="menuospite"),
    path("settings", ImpostazioniView.as_view(), name="impostazione"),
    path("match-list", views.PartecipaView.loadPartite, name="partecipa"),
    #path("login-control", views.controlUserData, name="controlUserData"),
    path("statistiche", views.StatisticheView.draw, name="statistiche"),
    path("credenziali", views.CredenzialiView.draw, name="credenziali"),
    #path("credenziali-aggiornamento",
         #views.CredenzialiView.updateData, name="updateData"),
    path("editor-mappa", views.MappaView.draw, name="editor"),
    path("save-mappa", views.MappaView.checkButton, name="checkButton"),
    #path("load-mappa", views.MappaView.loadMappaDifficile, name="loadMappa"),
    #path("logout", views.userLogout, name="logout"),
    path('creaPartita', views.PartitaView.creaPartita, name="creaPartita"),
    path('partecipaPartita<PartitaID>',
         views.PartitaView.partecipaPartita, name="partecipaPartita"),
]

RiskGame/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=45)
    last_name = forms.CharField(max_length=45)

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name',
                  'last_name', 'password1', 'password2']
        help_texts = {
            'username': "<br />L'username può contenere lettere, numeri e @/./+/-/_ soltanto",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = "<br />La password non può essere troppo simile alle tue altre informazioni personali<br />" \
                                             "La password deve contenere almeno 8 caratteri<br />" \
                                             "La password non può essere interamente numerica<br />" \
                                             "La password non può essere comune"
        self.fields['password2'].help_text = "<br />Inserisci la stessa password, per verificare"

RiskGame/views.py
import secrets
import constant
from django.shortcuts import render, redirect, reverse
from django.views.decorators.http import require_http_methods
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth import logout
from urllib import request
import views
from .forms import UserRegisterForm
from RiskGame.models import Statistiche, Mappa, Ospite, Partita, Continente, Territorio
from django.db.models import Count
import os
import random
from django.contrib.auth.models import User
import json
import math
from django.http import HttpResponse
import pytest
from urllib import request

ESTENSIONE = ".map.json"
PATH = 'static\Mappe'

# Create your views here.


class HomePageView(TemplateView):
    template_name = "home.html"

    # class LoginView(TemplateView):
    #   template_name = "login.html"

    """def controlUserData(request):
        if request.method == "POST":
            NickName = request.POST['nickname']
            Password = request.POST['password']
            if GiocatoreRegistrato.objects.filter(NickName=NickName, Password=Password).exists():
                return render(request, 'menu.html')
            else:
                messages.warning(request, 'i dati sono errati')
                return render(request, 'login.html')"""


class RegistrazioneView(TemplateView):
    template_name = "registrazione.html"

    @staticmethod
    @require_http_methods(["GET", "POST"])
    def register(request):
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')

            user = User.objects.filter(username=username).first()
            Statistiche.objects.create(
                IDGiocatore=user,
                NumeroPartiteVinte=0,
                NumeroPartitePerse=0,
                PercentualeVinte=0.0,
                NumeroScontriVinti=0,
                NumeroScontriPersi=0,
                NumeroScontriVintiATK=0,
                NumeroScontriPersiATK=0,
                NumeroScontriVintiDEF=0,
                NumeroScontriPersiDEF=0,
                PercentualeScontriVintiATK=0.0,
                NumeroPartiteGiocate=0
            )
            dirname = os.path.dirname(__file__)
            filename = os.path.join(dirname, PATH)
            Mappa.objects.filter(NomeMappa="MappaDefault").update(
                PercorsoMappa=filename)
            return redirect('home')
        else:
            form = UserRegisterForm()
        return render(request, 'registrazione.html', {'form': form})

    """def saveUserData(request):
        if request.method == "POST":
            NickName = request.POST['nickname']
            Nome = request.POST['nome']
            Cognome = request.POST['cognome']
            Email = request.POST['email']
            Password = request.POST['password']

            GiocatoreRegistrato.objects.create(Nome=Nome, Cognome=Cognome, NickName=NickName,
                                               Email=Email,
                                               Password=Password)
            messages.success(request, 'I dati sono stati salvati')
            return redirect(reverse('home'))"""


class MenuView(TemplateView):
    template_name = "menu.html"

    @staticmethod
    @require_http_methods(["GET", "POST"])
    def drawMenu(request):
        request.session['ospite'] = 'null'
        return render(request, MenuView.template_name)

    @staticmethod
    @require_http_methods(["GET", "POST"])
    def drawOspite(request):
        request.session['ospite'] = Ospite.assegnaOspite()
        return render(request, MenuView.template_name)


class ImpostazioniView(TemplateView):
    template_name = "impostazione.html"


class CreazioneView(TemplateView):

    @staticmethod
    @require_http_methods(["GET", "POST"])
    def draw(request):
        list_mappe = ["MappaDefault"]
        template_name = "creazione.html"
        if request.user.is_authenticated:
            username = User.objects.get(username=request.user.username)
            mappe = Mappa.objects.filter(Autore=username)
            for i in mappe:
                nome = i.NomeMappa
                if not nome in list_mappe:
                    list_mappe.append(nome)
        maps = {
            "nomi": list_mappe
        }
        return render(request, template_name, maps)


class PartecipaView(TemplateView):
    template_name = "partecipa.html"

    @staticmethod
    @require_http_methods(["GET", "POST"])
    def loadPartite(request):
        temp_data = Partita.objects.all()
        return render(request, "partecipa.html", {"partita_package": temp_data})


class PartitaView(TemplateView):
    template_name = "partita.html"
    template_creazione = "creazione.html"

    @staticmethod
    @require_http_methods(["GET", "POST"])
    def creaPartita(request):
        # Crea la partita nel DB, aggiunge il nuovo giocatore e lo reindirizza alla partita
        nome = request.POST['nome-mappa']
        difficolta = request.POST['difficolta']
        # nome_mappa = nome + "-" + "Difficile"
        nuovoID = Partita.getNuovoID()
        numGiocatori = request.POST['giocatori']
        mappa = None
        percorso = None
        intDiff = 0
        if nome == "nullo":
            messages.error(request, "Non hai selezionato alcuna mappa")
            return render(request, PartitaView.template_creazione)
        mappa = MappaView.checkMappa(request, nome, "Difficile")
        print(mappa)
        if difficolta == "Difficile":
            intDiff = 3
            # percorso = mappa.PercorsoMappa + "\\" + nome + ".map.json"
        elif difficolta == 'Semplice':
            intDiff = 1
            percorso = mappa.PercorsoMappa + "\\" + nome + ESTENSIONE
            file = open(percorso)
            data = json.load(file)
            MappaView.collassaConfiniDifficolta(request, data)
            percorso = mappa.PercorsoMappa
            MappaView.saveJson(nome, difficolta, percorso, data)
            file.close()
            MappaView.saveMappaEditor(request)
        elif difficolta == 'Media':
            intDiff = 2
            percorso = mappa.PercorsoMappa + "\\" + nome + ESTENSIONE
            file = open(percorso)
            data = json.load(file)
            MappaView.collassaConfiniDifficolta(request, data)
            percorso = mappa.PercorsoMappa
            MappaView.saveJson(nome, difficolta, percorso, data)
            file.close()
            MappaView.saveMappaEditor(request)

        """if difficolta == "Difficile" and nome != "MappaDefault":
            username = User.objects.get(username=request.user.username)
            mappa = Mappa.objects.filter(NomeMappa=nome, Difficolta=difficolta, Autore=username).first()
            #percorso = mappa.PercorsoMappa + "\\" + nome + ".map.json"
            intDiff = 3
        else:
            if request.user.is_authenticated:
                username = User.objects.get(username=request.user.username)
                if nome != "MappaDefault":
                    mappa = Mappa.objects.filter(NomeMappa=nome, Autore=username, Difficolta="Difficile").first()
                    percorso = mappa.PercorsoMappa + "\\" + nome + "-" + difficolta + ".map.json"
            else:
                mappa = Mappa.objects.filter(NomeMappa=nome, Difficolta="Difficile").first()
                percorso = mappa.PercorsoMappa + "\\" + nome + ".map.json"""
        n_continenti = Continente.objects.filter(Mappa=mappa).count()
        PartitaView.collassaGiocatori(
            request, nome, difficolta, n_continenti, numGiocatori)
        # mappa = Mappa.objects.filter(NomeMappa=nome, Autore=username, Difficolta= difficolta).first()
        if int(numGiocatori) <= n_continenti:
            Partita.objects.create(IDPartita=nuovoID, NumeroGiocatori=numGiocatori,
                                   Difficolta=intDiff, Mappa=mappa)
            if (request.user.is_authenticated):
                Partita.objects.get(
                    IDPartita=nuovoID).Giocatori.add(request.user)
            else:
                print(request.session['ospite'])
                ospite = Ospite.objects.get(Nickname=request.session['ospite'])
                Partita.objects.get(IDPartita=nuovoID).Ospiti.add(ospite)

            return redirect(reverse('RiskGame:partecipaPartita', kwargs={'PartitaID': nuovoID}))
        else:
            messages.error(
                request, "Il numero di giocatori inserito non è compatibile con la mappa")
            return render(request, PartitaView.template_creazione)

    @staticmethod
    @require_http_methods(["GET", "POST"])
    def partecipaPartita(request, PartitaID):
        # Aggiunge il giocatore alla lista giocatori e lo reindirizza alla partita
        partita = Partita.objects.get(IDPartita=PartitaID)
        if request.user.is_authenticated:
            partita.Giocatori.add(request.user)
        else:
            ospite = Ospite.objects.get(Nickname=request.session['ospite'])
            partita.Ospiti.add(ospite)
        return render(request, "partita.html", {"Partita": partita, "PartitaID": PartitaID,
                                                "Ospite": request.session['ospite']})

    @staticmethod
    @require_http_methods(["GET", "POST"])
    def collassaGiocatori(request, nome, difficolta, n_continenti, numGiocatori):
        if "collassaGiocatori" in request.POST:
            if n_continenti != int(numGiocatori):
                mappa = MappaView.checkMappa(request, nome, difficolta)
                if difficolta == "Difficile":
                    percorso = mappa.PercorsoMappa + "\\" + nome + ESTENSIONE
                else:
                    percorso = mappa.PercorsoMappa + "\\" + nome + "-" + difficolta + ESTENSIONE
                print(percorso)
                file = open(percorso)
                data = json.load(file)
                MappaView.collassaConfiniGiocatori(

RiskGame/templates/base.html
{% load bootstrap5 %}
{% load static %}

<!DOCTYPE html>
<html lang="it">

<head>








    <link rel="stylesheet" href="{% static 'Sfondo.css' %}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static 'jquery.js' %}" defer=""></script>
    <link rel="stylesheet" href="{% static 'Info.css' %}" media="screen">



    <link rel="stylesheet" type="text/css" href="{% static 'RiskGame/main.css' %}">
    <!-- Required meta tags -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'Info.css' %}" media="screen">

    <title>RiskGame!</title>
    <style>
        section {
            padding: 10vh 0;
        }

        body {
            background-color: #f8f9fa;
        }
    </style>
</head>


<body>
    <!--<div class="bg-image" style="background-image: url('{% static 'SfondoMappa.png'%}')">-->

    <header class=" site-header">

        <nav class="navbar navbar-expand-lg bg-steel fixed-top">
            <div class="container-fluid">
                <a href="{% url 'home' %}" class=" navbar-brand">
                    <img src=" {% static 'Home/MapBackground.png' %}" width=" 30" height="30" alt="">
                    RiskGame
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'RiskGame:menu' %}">Gioca!</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{% url 'RiskGame:menuospite' %}">Gioca!</a>
                        {% endif %}
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav flex-end">

                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown justify-content-center">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                {{ user.username }}
                            </a>

                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'RiskGame:credenziali' %}">
                                        Credenziali</a></li>
                                <li><a class="dropdown-item" href="{% url 'RiskGame:editor' %}">Mappe</a>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'RiskGame:statistiche' %}">Statistiche</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item nav-item" href="{% url 'logout' %}">Logout</a></li>
                            </ul>

                        </li>


                        {% elif request.path == '/' %}

                        <a class="nav-item nav-link" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button"
                            aria-controls="offcanvasExample">Login</a>

                        <a class="nav-item nav-link" href="{% url 'RiskGame:registrazione' %}">Registrazione</a>
                        <a class="nav-item nav-link" href="{% url 'RiskGame:menu' %}">Ospite</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </nav>
    </header>

    {% block content %}

    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>






</body>

</html>

RiskGame/templates/credenziali.html
{% extends "base.html" %}
{% block content %}

<style>
  section {
    padding: 5vh 0;
  }

  .formp {
    transform: scale(0.9);
  }
</style>

<section id="intro">
  <div class="container-lg">
    <div class="row">
      <div class="col-md-5 text-md-start">

        {% load crispy_forms_tags %}
        <div class="selection">
          <form method="post" class="formp">
            {% csrf_token %}
            {{ userprofile_form|crispy }}
            <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Modifica le tue credenziali</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

</section>





{% endblock content %}

RiskGame/templates/impostazione.html
<!DOCTYPE html>
<html style="font-size: 16px;" xml:lang>
{% load static %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content=""><meta name="description" content=""><meta name="page_type" content="np-template-header-footer-from-plugin">
    <title></title>
    <link rel="stylesheet" href="{% static 'nicepage.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'Sfondo.css' %}" media="screen">
    <script class="u-script" type="text/javascript" src="{% static 'jquery.js' %}" defer=""></script>
    <script class="u-script" type="text/javascript" src="{% static 'nicepage.js' %}" defer=""></script>

<body class="body" data-style="blank" data-posts="" data-global-section-properties="{&quot;colorings&quot;:{&quot;light&quot;:[&quot;clean&quot;],&quot;colored&quot;:[&quot;clean&quot;],&quot;dark&quot;:[&quot;dark&quot;]}}" data-source="blank" data-page-sections-style="[]" data-page-coloring-types="{&quot;light&quot;:[&quot;clean&quot;],&quot;colored&quot;:[&quot;clean&quot;],&quot;dark&quot;:[&quot;dark&quot;]}" data-page-category="&quot;Basic&quot;"><section class="u-clearfix u-custom-color-1 u-block-702b-1" custom-posts-hash="[]" data-style="blank" data-section-properties="{&quot;margin&quot;:&quot;none&quot;,&quot;stretch&quot;:true}" id="sec-341e" data-source="Blank" data-id="702b">
  <header class="u-clearfix u-custom-color-1 u-header u-header" id="sec-3a71" data-animation-name="" data-animation-duration="0" data-animation-delay="0" data-animation-direction=""><div class="u-align-left u-clearfix u-sheet u-valign-middle u-sheet-1">
        <a href="{% url 'RiskGame:menu' %}" class="u-border-none u-btn u-button-style u-custom-color-4 u-hover-palette-2-dark-2 u-btn-1">Menu<br>
        </a>
      </div><style class="u-sticky-style" data-style-id="038f">.u-sticky-fixed.u-sticky-038f:before, .u-body.u-sticky-fixed .u-sticky-038f:before {
border: top right !important
}</style></header>
    <div class="u-clearfix u-sheet u-block-702b-2">
      <a href="{% url 'RiskGame:credenziali' %}" class="u-border-none u-btn u-button-style u-custom-color-4 u-hover-palette-2-dark-2 u-block-702b-3">Modifica le tue credenziali</a>
      <a href="{% url 'RiskGame:editor' %}" class="u-border-none u-btn u-button-style u-custom-color-4 u-hover-palette-2-dark-2 u-block-702b-4">Mappe<br></a>
      <a href="{% url 'RiskGame:statistiche' %}" class="u-border-none u-btn u-button-style u-custom-color-4 u-hover-palette-2-dark-2 u-block-702b-5">Statistiche account<br></a></div>
<style data-mode="XL" data-visited="true">@media (min-width: 1200px) {
  .u-block-702b-2 {
    min-height: 500px;
  }
  .u-block-702b-3 {
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    background-image: none;
    align-self: center;
    margin-top: 78px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-702b-4 {
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    background-image: none;
    align-self: center;
    margin-top: 64px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-702b-5 {
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    background-image: none;
    align-self: center;
    margin-top: 78px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 60px;
  }
}</style><style data-mode="LG">@media (max-width: 1199px) and (min-width: 992px) {
  .u-block-702b-2 {
    min-height: 500px;
  }
  .u-block-702b-3 {
    background-image: none;
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    align-self: center;
    margin-top: 78px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-702b-4 {
    background-image: none;
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    align-self: center;
    margin-top: 64px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-702b-5 {
    background-image: none;
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    align-self: center;
    margin-top: 78px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 60px;
  }
}</style><style data-mode="MD">@media (max-width: 991px) and (min-width: 768px) {
  .u-block-702b-2 {
    min-height: 500px;
  }
  .u-block-702b-3 {
    background-image: none;
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    align-self: center;
    margin-top: 78px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-702b-4 {
    background-image: none;
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    align-self: center;
    margin-top: 64px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-702b-5 {
    background-image: none;
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    align-self: center;
    margin-top: 78px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 60px;
  }
}</style><style data-mode="SM">@media (max-width: 767px) and (min-width: 576px) {
  .u-block-702b-2 {
    min-height: 500px;
  }
  .u-block-702b-3 {
    background-image: none;
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    align-self: center;
    margin-top: 78px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-702b-4 {
    background-image: none;
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    align-self: center;
    margin-top: 64px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-702b-5 {
    background-image: none;
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    align-self: center;
    margin-top: 78px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 60px;
  }
}</style><style data-mode="XS">@media (max-width: 575px) {
  .u-block-702b-2 {
    min-height: 500px;
  }
  .u-block-702b-3 {
    background-image: none;
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    align-self: center;
    margin-top: 78px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-702b-4 {
    background-image: none;
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    align-self: center;
    margin-top: 64px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 0;
  }
  .u-block-702b-5 {
    background-image: none;
    letter-spacing: 1px;
    border-style: none;
    font-weight: 700;
    text-transform: uppercase;
    align-self: center;
    margin-top: 78px;
    margin-left: auto;
    margin-right: auto;
    margin-bottom: 60px;
  }
}</style></section>
</body></html>

RiskGame/templates/logout.html
{% extends "base.html" %}
{% block content %}
<style>
    section {
        padding: 10vh 0;
    }
</style>

<section id="intro">
    <div class="container-lg">
        <div class="row g-4 justify-content-center align-items-center">
            <div class="col-md-5 text-center text-md-start">
                <p class="lead my-4 text-muted">Hai Eseguito il Logout!
                    Torna alla Home!
                <div class="border-top pt-4">
                    <small class="text-muted">
                        <a class="btn-secondary btn-lg" href="{% url 'home' %}">Home!</a>
                    </small>
                </div>
                </p>



            </div>

        </div>
    </div>
</section>





{% endblock content %}